name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Cache pip dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install kivy buildozer

    - name: Build APK
      run: |
        sudo apt update
        sudo apt install -y python3-pip openjdk-11-jdk git zip unzip
        pip install --upgrade cython==0.29.19 virtualenv
        
        # Initialize Buildozer if not already initialized
        if [ ! -f buildozer.spec ]; then buildozer init; fi
        
        # Build the APK
        buildozer -v android debug
      env:
        ANDROIDSDK: ${{ github.workspace }}/.buildozer/android/platform/android-sdk
        ANDROIDNDK: ${{ github.workspace }}/.buildozer/android/platform/android-ndk-r21d

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: my-android-app
        path: bin/
