name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Docker
      run: |
        docker pull kivy/buildozer:latest

    - name: Build APK with Docker
      run: |
        docker run --rm \
          --volume "${GITHUB_WORKSPACE}:/home/user/hostcwd" \
          --workdir "/home/user/hostcwd" \
          kivy/buildozer:latest \
          /bin/bash -c "buildozer init && buildozer android debug"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk
        if-no-files-found: error
