name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: kivy/buildozer:latest

    steps:
    - uses: actions/checkout@v4

    - name: Build APK
      run: |
        buildozer android debug

    - uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk
