name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - uses: actions/cache@v4
      with:
        path: ~/.buildozer
        key: buildozer-deps-${{ hashFiles('buildozer.spec') }}

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip build-essential git python3 python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev openjdk-11-jdk
        pip install --upgrade pip
        pip install buildozer
        pip install cython==0.29.19

    - name: Build APK
      run: |
        buildozer android debug
      env:
        BUILDOZER_WARN_ON_ROOT: 1
        PATH: "$PATH:$ANDROID_HOME/platform-tools"

    - uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk
