name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip openjdk-11-jdk git zip unzip
        pip install --upgrade cython==0.29.19 virtualenv kivy buildozer

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Install Android SDK components
      run: |
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"

    - name: Build APK
      run: |
        if [ ! -f buildozer.spec ]; then buildozer init; fi
        buildozer -v android debug
      env:
        ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: my-android-app
        path: bin/
